version: 2
jobs:
  build:
    docker:
      - image: tmecklem/docker-scenic:1.8.1
        environment:
          MIX_ENV: test

    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix local.rebar --force

      - run:
          name: "ELIXIR_VERSION.lock"
          command: echo "${ELIXIR_VERSION}" > ELIXIR_VERSION.lock
      - run:
          name: "OTP_VERSION.lock"
          command: echo "${OTP_VERSION}" > OTP_VERSION.lock

      # makerion
      - restore_cache:
          keys:
            - v1-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "makerion/mix.lock" }}
            - v1-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}
      - run:
          name: Compile Makerion
          command: mix do deps.get, compile
          working_directory: ~/project/makerion
      - save_cache:
          key: v1-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "makerion/mix.lock" }}
          paths:
            - makerion/deps
            - makerion/_build
      - save_cache:
          key: v1-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}
          paths:
            - makerion/deps
            - makerion/_build

      # makerion_web
      - restore_cache:
          keys:
            - v1-web-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "makerion_web/mix.lock" }}
            - v1-web-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}
      - run:
          name: Compile Makerion Web
          command: mix do deps.get, compile
          working_directory: ~/project/makerion_web
      - save_cache:
          key: v1-web-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "makerion_web/mix.lock" }}
          paths:
            - makerion_web/deps
            - makerion_web/_build
      - save_cache:
          key: v1-web-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}
          paths:
            - makerion_web/deps
            - makerion_web/_build

      # makerion_kiosk
      - restore_cache:
          keys:
            - v1-kiosk-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "makerion_kiosk/mix.lock" }}
            - v1-kiosk-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}
      - run:
          name: Compile Makerion Kiosk
          command: mix do deps.get, compile
          working_directory: ~/project/makerion_kiosk
      - save_cache:
          key: v1-kiosk-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "makerion_kiosk/mix.lock" }}
          paths:
            - makerion_kiosk/deps
            - makerion_kiosk/_build
      - save_cache:
          key: v1-kiosk-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}
          paths:
            - makerion_kiosk/deps
            - makerion_kiosk/_build

      # makerion_firmware
      - restore_cache:
          keys:
            - v1-firmware-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "makerion_firmware/mix.lock" }}
            - v1-firmware-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}
      - run:
          name: Compile Makerion Firmware
          command: mix do deps.get, compile
          working_directory: ~/project/makerion_firmware
      - save_cache:
          key: v1-firmware-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "makerion_firmware/mix.lock" }}
          paths:
            - makerion_firmware/deps
            - makerion_firmware/_build
      - save_cache:
          key: v1-firmware-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}
          paths:
            - makerion_firmware/deps
            - makerion_firmware/_build

      - persist_to_workspace:
          root: .
          paths:
            - .circleci
            - .dialyzer-ignore.exs
            - .git
            - .gitignore
            - ELIXIR_VERSION.lock
            - OTP_VERSION.lock
            - makerion
            - makerion_firmware
            - makerion_kiosk
            - makerion_web

  makerion_credo:
    docker:
      - image: circleci/elixir:1.8.1
        environment:
          MIX_ENV: test

    steps:
      - attach_workspace:
          at: .

      - run:
          command: mix local.hex --force
          working_directory: ~/project/makerion

      - run:
          command: mix credo --strict
          working_directory: ~/project/makerion

  makerion_dialyzer:
    docker:
      - image: circleci/elixir:1.8.1
        environment:
          MIX_ENV: test

    steps:
      - attach_workspace:
          at: .

      - run:
          command: mix local.hex --force
          working_directory: ~/project/makerion

      - restore_cache:
          keys:
            - v1-mix-dialyzer-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "makerion/mix.lock" }}
            - v1-mix-dialyzer-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}

      - run:
          name: Unpack PLT cache
          command: |
            mkdir -p _build/test
            cp plts/dialyxir*.plt _build/test/ || true
            mkdir -p ~/.mix
            cp plts/dialyxir*.plt ~/.mix/ || true
          working_directory: ~/project/makerion

      - run:
          command: mix dialyzer --plt
          working_directory: ~/project/makerion

      - run:
          name: Pack PLT cache
          command: |
            mkdir -p plts
            cp _build/test/dialyxir*.plt plts/
            cp ~/.mix/dialyxir*.plt plts/
          working_directory: ~/project/makerion

      - save_cache:
          key: v1-mix-dialyzer-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "makerion/mix.lock" }}
          paths:
            - plts
      - save_cache:
          key: v1-mix-dialyzer-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}
          paths:
            - plts

      - run:
          command: mix dialyzer --halt-exit-status
          working_directory: ~/project/makerion

  makerion_test:
    docker:
      - image: circleci/elixir:1.8.1
        environment:
          MIX_ENV: test

    steps:
      - attach_workspace:
          at: .

      - run:
          command: mix local.hex --force
          working_directory: ~/project/makerion
      - run:
          command: mix local.rebar --force
          working_directory: ~/project/makerion

      - run:
          command: mix do ecto.create, ecto.migrate
          working_directory: ~/project/makerion
      - run:
          name: mix test
          command: |
            if [[ -z "$COVERALLS_REPO_TOKEN" ]]; then
              mix coveralls.html
            else
              mix coveralls.circle ||
                (retval=$? && curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$CIRCLE_WORKFLOW_WORKSPACE_ID&payload[status]=done" && return $retval)
            fi
          working_directory: ~/project/makerion

      - store_artifacts:
          path: makerion/cover/excoveralls.html
      - store_test_results:
          path: makerion/_build/test/junit


  makerion_web_build:
    docker:
      - image: circleci/elixir:1.8.1
        environment:
          MIX_ENV: test

    steps:
      - attach_workspace:
          at: .

      - restore_cache:
          keys:
            - v1-web-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "makerion_web/mix.lock" }}
            - v1-web-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}

      - run:
          command: mix deps.get
          working_directory: ~/project/makerion_web

      - run:
          command: mix compile
          working_directory: ~/project/makerion_web

      - save_cache:
          key: v1-web-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "makerion_web/mix.lock" }}
          paths:
            - makerion_web/deps
            - makerion_web/_build
      - save_cache:
          key: v1-web-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}
          paths:
            - makerion_web/deps
            - makerion_web/_build

      - persist_to_workspace:
          root: .
          paths:
            - makerion_web

  makerion_web_credo:
    docker:
      - image: circleci/elixir:1.8.1
        environment:
          MIX_ENV: test

    steps:
      - attach_workspace:
          at: .

      - run:
          command: mix local.hex --force
          working_directory: ~/project/makerion_web

      - run:
          command: mix credo --strict
          working_directory: ~/project/makerion_web

workflows:
  version: 2
  primary:
    jobs:
      - build
      - makerion_credo:
          requires:
            - build
      - makerion_dialyzer:
          requires:
            - build
      - makerion_test:
          requires:
            - build
      - makerion_web_build:
          requires:
            - build
      - makerion_web_credo:
          requires:
            - build
