version: 2.1

install_hex_rebar: &install_hex_rebar
  run:
    name: Install hex and rebar
    command: |
      mix local.hex --force
      mix local.rebar --force
install_nerves_bootstrap: &install_nerves_bootstrap
  run:
    name: Install nerves_bootstrap
    command: |
      mix archive.install hex nerves_bootstrap "~> 1.0" --force
jobs:
  build:
    docker:
      - image: tmecklem/elixir:1.8.1-node-browsers-scenic
        environment:
          MIX_ENV: test

    steps:
      - checkout
      - <<: *install_hex_rebar
      - <<: *install_nerves_bootstrap

      - run:
          name: "ELIXIR_VERSION.lock"
          command: echo "${ELIXIR_VERSION}" > ELIXIR_VERSION.lock
      - run:
          name: "OTP_VERSION.lock"
          command: echo "${OTP_VERSION}" > OTP_VERSION.lock

      # makerion
      - restore_cache:
          keys:
            - v2-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "makerion/mix.lock" }}
            - v2-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}
      - run:
          name: Compile Makerion
          command: mix do deps.get, compile
          working_directory: ~/project/makerion
      - save_cache:
          key: v2-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "makerion/mix.lock" }}
          paths:
            - makerion/deps
            - makerion/_build
      - save_cache:
          key: v2-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}
          paths:
            - makerion/deps
            - makerion/_build

      # makerion_web
      - restore_cache:
          keys:
            - v2-web-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "makerion_web/mix.lock" }}
            - v2-web-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}
      - run:
          name: Compile Makerion Web
          command: mix do deps.get, compile
          working_directory: ~/project/makerion_web
      - save_cache:
          key: v2-web-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "makerion_web/mix.lock" }}
          paths:
            - makerion_web/deps
            - makerion_web/_build
      - save_cache:
          key: v2-web-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}
          paths:
            - makerion_web/deps
            - makerion_web/_build

      # makerion_kiosk
      - restore_cache:
          keys:
            - v2-kiosk-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "makerion_kiosk/mix.lock" }}
            - v2-kiosk-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}
      - run:
          name: Compile Makerion Kiosk
          command: mix do deps.get, compile
          working_directory: ~/project/makerion_kiosk
      - save_cache:
          key: v2-kiosk-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "makerion_kiosk/mix.lock" }}
          paths:
            - makerion_kiosk/deps
            - makerion_kiosk/_build
      - save_cache:
          key: v2-kiosk-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}
          paths:
            - makerion_kiosk/deps
            - makerion_kiosk/_build

      # makerion_firmware
      - restore_cache:
          keys:
            - v2-firmware-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "makerion_firmware/mix.lock" }}
            - v2-firmware-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}
      - run:
          name: Compile Makerion Firmware
          command: mix do deps.get, compile
          working_directory: ~/project/makerion_firmware
      - save_cache:
          key: v2-firmware-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "makerion_firmware/mix.lock" }}
          paths:
            - makerion_firmware/deps
            - makerion_firmware/_build
      - save_cache:
          key: v2-firmware-mix-compile-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}
          paths:
            - makerion_firmware/deps
            - makerion_firmware/_build

      - persist_to_workspace:
          root: .
          paths:
            - .circleci
            - .dialyzer-ignore.exs
            - .git
            - .gitignore
            - ELIXIR_VERSION.lock
            - OTP_VERSION.lock
            - makerion
            - makerion_firmware
            - makerion_kiosk
            - makerion_web

  makerion_test:
    docker:
      - image: tmecklem/elixir:1.8.1-node-browsers-scenic
        environment:
          MIX_ENV: test

    steps:
      - attach_workspace:
          at: .
      - <<: *install_hex_rebar

      - run:
          name: Create Test Database
          command: mix do ecto.create, ecto.migrate
          working_directory: ~/project/makerion
      - run:
          name: mix test
          command: |
            if [[ -z "$COVERALLS_REPO_TOKEN" ]]; then
              mix coveralls.html
            else
              mix coveralls.circle ||
                (retval=$? && curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$CIRCLE_WORKFLOW_WORKSPACE_ID&payload[status]=done" && return $retval)
            fi
          working_directory: ~/project/makerion

      - store_artifacts:
          path: makerion/cover/excoveralls.html
      - store_test_results:
          path: makerion/_build/test/junit

  makerion_dialyzer:
    docker:
      - image: tmecklem/elixir:1.8.1-node-browsers-scenic
        environment:
          MIX_ENV: test

    steps:
      - attach_workspace:
          at: .
      - <<: *install_hex_rebar
      - <<: *install_nerves_bootstrap

      - restore_cache:
          keys:
            - v2-mix-dialyzer-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "makerion/mix.lock" }}
            - v2-mix-dialyzer-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}

      - run:
          command: mix dialyzer --plt
          working_directory: ~/project/makerion
          no_output_timeout: 20m

      - save_cache:
          key: v2-mix-dialyzer-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "makerion/mix.lock" }}
          paths:
            - makerion/priv/plts
      - save_cache:
          key: v2-mix-dialyzer-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}
          paths:
            - makerion/priv/plts

      - run:
          command: mix dialyzer --halt-exit-status
          working_directory: ~/project/makerion
          no_output_timeout: 20m

  kiosk_test:
    docker:
      - image: tmecklem/elixir:1.8.1-node-browsers-scenic
        environment:
          MIX_ENV: test

    steps:
      - attach_workspace:
          at: .
      - <<: *install_hex_rebar

      - run:
          name: Create Test Database
          command: mix do ecto.create, ecto.migrate
          working_directory: ~/project/makerion
      - run:
          name: mix test
          command: |
            if [[ -z "$COVERALLS_REPO_TOKEN" ]]; then
              mix coveralls.html
            else
              mix coveralls.circle ||
                (retval=$? && curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$CIRCLE_WORKFLOW_WORKSPACE_ID&payload[status]=done" && return $retval)
            fi
          working_directory: ~/project/makerion_kiosk

      - store_artifacts:
          path: makerion_kiosk/cover/excoveralls.html
      - store_test_results:
          path: makerion_kiosk/_build/test/junit

  kiosk_dialyzer:
    docker:
      - image: tmecklem/elixir:1.8.1-node-browsers-scenic
        environment:
          MIX_ENV: test

    steps:
      - attach_workspace:
          at: .
      - <<: *install_hex_rebar
      - <<: *install_nerves_bootstrap

      - restore_cache:
          keys:
            - v2-kiosk-mix-dialyzer-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "makerion_kiosk/mix.lock" }}
            - v2-kiosk-mix-dialyzer-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}

      - run:
          command: mix dialyzer --plt
          working_directory: ~/project/makerion_kiosk
          no_output_timeout: 20m

      - save_cache:
          key: v2-kiosk-mix-dialyzer-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "makerion_kiosk/mix.lock" }}
          paths:
            - makerion_kiosk/priv/plts
      - save_cache:
          key: v2-kiosk-mix-dialyzer-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}
          paths:
            - makerion_kiosk/priv/plts

      - run:
          command: mix dialyzer --halt-exit-status
          working_directory: ~/project/makerion_kiosk
          no_output_timeout: 20m

  web_test:
    docker:
      - image: tmecklem/elixir:1.8.1-node-browsers-scenic
        environment:
          MIX_ENV: test

    steps:
      - attach_workspace:
          at: .
      - <<: *install_hex_rebar

      - run:
          name: Create Test Database
          command: mix do ecto.create, ecto.migrate
          working_directory: ~/project/makerion
      - run:
          name: generate static assets
          command: npm install && npm run deploy
          working_directory: ~/project/makerion_web/assets
      - run:
          name: phx.digest
          command: mix phx.digest
          working_directory: ~/project/makerion_web
      - run:
         name: Start Chrome Driver
         command: /usr/local/bin/chromedriver
         background: true
      - run:
          name: mix test
          command: |
            if [[ -z "$COVERALLS_REPO_TOKEN" ]]; then
              mix coveralls.html
            else
              mix coveralls.circle ||
                (retval=$? && curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$CIRCLE_WORKFLOW_WORKSPACE_ID&payload[status]=done" && return $retval)
            fi
          working_directory: ~/project/makerion_web

      - store_artifacts:
          path: makerion_web/screenshots
          prefix: screenshots
      - store_artifacts:
          path: makerion_web/cover/excoveralls.html
      - store_test_results:
          path: makerion_web/_build/test/junit

  web_dialyzer:
    docker:
      - image: tmecklem/elixir:1.8.1-node-browsers-scenic
        environment:
          MIX_ENV: test

    steps:
      - attach_workspace:
          at: .
      - <<: *install_hex_rebar
      - <<: *install_nerves_bootstrap

      - restore_cache:
          keys:
            - v2-web-mix-dialyzer-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "makerion_web/mix.lock" }}
            - v2-web-mix-dialyzer-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}

      - run:
          command: mix dialyzer --plt
          working_directory: ~/project/makerion_web
          no_output_timeout: 20m

      - save_cache:
          key: v2-web-mix-dialyzer-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "makerion_web/mix.lock" }}
          paths:
            - makerion_web/priv/plts
      - save_cache:
          key: v2-web-mix-dialyzer-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}
          paths:
            - makerion_web/priv/plts

      - run:
          command: mix dialyzer --halt-exit-status
          working_directory: ~/project/makerion_web
          no_output_timeout: 20m

  firmware_test:
    docker:
      - image: tmecklem/elixir:1.8.1-node-browsers-scenic
        environment:
          MIX_ENV: test

    steps:
      - attach_workspace:
          at: .
      - <<: *install_hex_rebar
      - <<: *install_nerves_bootstrap

      - run:
          name: Create Test Database
          command: mix do ecto.create, ecto.migrate
          working_directory: ~/project/makerion
      - run:
          name: mix test
          command: |
            if [[ -z "$COVERALLS_REPO_TOKEN" ]]; then
              mix coveralls.html
            else
              mix coveralls.circle ||
                (retval=$? && curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$CIRCLE_WORKFLOW_WORKSPACE_ID&payload[status]=done" && return $retval)
            fi
          working_directory: ~/project/makerion_firmware

      - store_artifacts:
          path: makerion_firmware/cover/excoveralls.html
      - store_test_results:
          path: makerion_firmware/_build/test/junit

  firmware_dialyzer:
    docker:
      - image: tmecklem/elixir:1.8.1-node-browsers-scenic
        environment:
          MIX_ENV: test

    steps:
      - attach_workspace:
          at: .
      - <<: *install_hex_rebar
      - <<: *install_nerves_bootstrap

      - restore_cache:
          keys:
            - v2-firmware-mix-dialyzer-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "makerion_firmware/mix.lock" }}
            - v2-firmware-mix-dialyzer-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}

      - run:
          command: mix dialyzer --plt
          working_directory: ~/project/makerion_firmware
          no_output_timeout: 20m

      - save_cache:
          key: v2-firmware-mix-dialyzer-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}-{{ checksum "makerion_firmware/mix.lock" }}
          paths:
            - makerion_firmware/priv/plts
      - save_cache:
          key: v2-firmware-mix-dialyzer-{{ checksum "OTP_VERSION.lock" }}-{{ checksum "ELIXIR_VERSION.lock" }}
          paths:
            - makerion_firmware/priv/plts

      - run:
          command: mix dialyzer --halt-exit-status
          working_directory: ~/project/makerion_firmware
          no_output_timeout: 20m

  credo:
    parameters:
      project_name:
        description: "project name"
        type: string
        default: makerion
    docker:
      - image: tmecklem/elixir:1.8.1-node-browsers-scenic
        environment:
          MIX_ENV: test
    steps:
      - attach_workspace:
          at: .
      - <<: *install_hex_rebar
      - run:
          command: mix credo --strict
          working_directory: ~/project/<< parameters.project_name >>

workflows:
  version: 2
  primary:
    jobs:
      - build
      - makerion_test:
          requires:
            - build
      - makerion_dialyzer:
          requires:
            - makerion_credo
            - makerion_test
      - credo:
          project_name: makerion
          name: makerion_credo
          requires:
            - build
      - credo:
          project_name: makerion_web
          name: web_credo
          requires:
            - build
      - credo:
          project_name: makerion_kiosk
          name: kiosk_credo
          requires:
            - build
      - credo:
          project_name: makerion_firmware
          name: firmware_credo
          requires:
            - build
      - kiosk_test:
          requires:
            - build
      - kiosk_dialyzer:
          requires:
            - kiosk_credo
            - kiosk_test
      - web_test:
          requires:
            - build
      - web_dialyzer:
          requires:
            - web_credo
            - web_test
      - firmware_test:
          requires:
            - build
      - firmware_dialyzer:
          requires:
            - firmware_credo
            - firmware_test
